version: '3.0'
services:
  eosio-contract-api-filler:
    container_name: eosio-contract-api-filler
    build: .
    command: yarn run start:filler
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - ./test-config:/home/application/app/config
    networks:
      - eosio-contract-api
  eosio-contract-api-server:
    container_name: eosio-contract-api-server
    build: .
    command: yarn run start:server
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config:/home/application/app/config
    networks:
      - eosio-contract-api
  redis:
    container_name: eosio-contract-api-redis
    image: redis:5-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - eosio-contract-api
  postgres:
    container_name: eosio-contract-api-postgres
    image: postgres:13
    restart: on-failure
    shm_size: '8gb'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=changeme'
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data-full:/var/lib/postgresql/data
      - ./docker/postgres/dump:/var/lib/postgresql/dump
    networks:
      - eosio-contract-api

networks:
  eosio-contract-api:
    driver: bridge
